[package]
name = "webracwl_wikipedia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wikipedia = "0.4.0"
rayon = "1.7.0"
